# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('quoteby', models.CharField(max_length=45)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='alias_name',
        ),
        migrations.AddField(
            model_name='quote',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_created', to='examapp.User'),
        ),
        migrations.AddField(
            model_name='quote',
            name='favbyuser',
            field=models.ManyToManyField(related_name='favquote', to='examapp.User'),
        ),
    ]
